apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    app.kubernetes.io/part-of: microkube
    env: demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: loadtest
  labels:
    app.kubernetes.io/part-of: microkube
    env: loadtest
